//Errors
export const GENERIC_ERROR = 'GENERIC_ERROR'

export const SET_USER = 'SET_USER';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const PAY_MEMBERSHIP = 'PAY_MEMBERSHIP';
export const CANCEL_MEMBERSHIP = 'CANCEL_MEMBERSHIP';
export const RESET_GENERIC_ERROR = 'RESET_GENERIC_ERROR';
export const RESET_IS_MEMBER = 'RESET_IS_MEMBER';
export const GET_USER_ID = 'GET_USER_ID';

export const UPLOAD_IMAGE_SUCCES= 'UPLOAD_IMAGE_SUCCESS'


//login
export const LOGIN_USERMEMBER = 'LOGIN_USER';
export const VERIFY_USERNAME = 'VERIFY_USERNAME';
export const VERIFY_ISMEMBER = 'VERIFY_ISMEMBER';


//makeAppoiment
export const DOCTOR_FILTERING = 'DOCTOR_FILTERING';
export const ALL_SCHEDULE = "ALL_SCHEDULE";
export const NOTHING = 'NOTHING';

//doctors
export const GET_DOCTORS ="GET_DOCTORS";
export const GET_SPECIALTIES = "GET_SPECIALTIES";

//products
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_ALL_PRODUCTS_PAGE = 'GET_ALL_PRODUCTS_PAGE';

//shoppingCart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const GET_CART_USER = 'GET_CART_USER';
export const PAYMENT = 'PAYMENT';
export const DEFAUL_STATE = 'DEFAUL_STATE';
