export const SET_USER = 'SET_USER';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const PAY_MEMBERSHIP = 'PAY_MEMBERSHIP';
export const CANCEL_MEMBERSHIP = 'CANCEL_MEMBERSHIP';